### ISSUE TITLE
Is it possible to replace nodes with images?

### ISSUE THREAD

**Issue by fwitte** [jerosoler/Drawflow#167]
Hi,
I am programming an open source thermal engineering simulator. In commercial software there is usually a GUI for flowsheeting, in my software people need to write code. While this might even be faster/flexible for very experienced users, it would be nice to have such a feature.

You library looks great and seems very promising for my issue. I have not yet dug deep into the code of Drawflow (as I am not experienced with .js anyway), therefore I have two questions, which I could not find respective issues for:

- Is it possible to replace the boxes with images (svg format)?
- And is it possible to then place the connectors at the respective places of the image? (The solution is somewhere here, I guess: https://github.com/jerosoler/Drawflow/issues/20)

I do not want a solution, just a quick answer, if that is possible, so I can evaluate if I dig deeper into the code :). If this question was already answered, maybe you can give me a hint where to look.

Thanks a lot!

A plant might look like this:

![refrigerator](https://user-images.githubusercontent.com/20252362/117280264-b6183580-ae62-11eb-8d1e-4b8cdf8f81d0.png)

**Comment by jerosoler** [comment]
Hi @fwitte 

If an image or a svg could be loaded, since the code is html of the node.

And with css you could move the points.
Correct here you can see how to move the inputs / outputs https://github.com/jerosoler/Drawflow/issues/20#issuecomment-679976512

Here's a quick test.

![image](https://user-images.githubusercontent.com/30957047/117344042-40818900-aea5-11eb-8cc2-ce4724cae899.png)

Jero

**Comment by fwitte** [comment]
Thanks a lot, will look into it then!
