### ISSUE TITLE
nodeChanged and/or dataUpdated

### ISSUE THREAD

**Issue by kit-oz** [jerosoler/Drawflow#214]
Hello.

For instant data synchronization, it is necessary to receive information about any data changes within Dataflow. But now at least the nodeChanged event is missing.
And ideally it should be one global event - something like dataChanged, which is triggered on any changes in the nodes / connections.

What do you think about this?

**Comment by jerosoler** [comment]
Hello @kit-oz 

Currently you can get all the information or almost. With the events:
`nodeCreated`, `nodeRemoved`, `nodeMoved`, `connectionCreated` and `connectionRemoved`.

I think a `nodeDataChanged` would be missing for the df- * attributes

Do you think any more would be missing?

**Comment by kit-oz** [comment]
Thanks for the quick response.

I am using Vue to edit node data something like this:

```js
async editNodeData() {
  node = this.editor.getNodeFromId(this.id)
  const newData = await this.editInModalForm(node.data)
  this.editor.updateNodeDataFromId(this.id, newData);
},
```
Add to `updateNodeDataFromId` (and possibly to `updateNodeValue`) dispatching `nodeDataChanged` looks like it should.

And I also noticed that the `clear` and` clearModuleSelected` methods do not dispatch the `moduleRemoved` event (which is already present in other cases)

**Comment by jerosoler** [comment]
Hi! 

added new event `nodeDataChanged` in version 0.0.46. Called only when df- * attributes are edited.

The `updateNodeDataFromId` method does not call `nodeDataChanged`, since it is called by the user, in any case when you call this method you can always call its update function.

The same thing happens with the `clear` function. The same is also true for the `import` function. That it is you who calls it via javascript, in any case you know that all modules are eliminated.

`clearModuleSelected` only removes the content, it does not remove the module.
