### ISSUE TITLE
Can't use style library like vuetify for my custom component

### ISSUE THREAD

**Issue by SilasNiewierra** [jerosoler/Drawflow#258]
Hey, 
I love the Drawflow library, and would like to style my Nodes.
I tried a simple Node with vuetify, but it looks like this.
![image](https://user-images.githubusercontent.com/55000832/134652583-eaa11032-7f84-44d4-8f64-675772a548f9.png)

My code for this node:
Trigger.vue
```
<template>
  <div class="header">
    <v-icon large color="green darken-2"> mdi-domain </v-icon>
    <div class="title">Trigger</div>
  </div>
  <hr />
  <div class="body">
    <p>If {{ triggerEvent }}</p>
    <v-btn>Click me</v-btn>
  </div>
</template>

<script lang="ts">
import { defineComponent } from '@vue/runtime-core'

export default defineComponent({
  data() {
    return {
      triggerEvent: '',
    }
  },
})
</script>
```

**Comment by jerosoler** [comment]
Hi @SilasNiewierra 

Are you using vue2?

How is the code you use for "new Drawflow"? Pass the param "this"

**Comment by jerosoler** [comment]
uhmmm... 

In vue 2 we could pass the instance. 
Example: code: 
```javascript
this.editor = new Drawflow(id, Vue, this);
```
https://vuejs.org/v2/api/#parent

The problem is the Vue3 `createApp` not is possible pass  parent instance. 

Actuallly draflow in vue 3 mount component with: 
```javascript
createApp({
render: h => h('<h1></h1>' props, options)
}).mount(content);
```

I haven't played much with vue3, can you think of a way to pass the instance?

Is it possible to assemble a component on the fly? Without createapp?

I've been looking at the documentation for vue3.
https://v3.vuejs.org/api/composition-api.html#getcurrentinstance

**Comment by SilasNiewierra** [comment]
Hi Jero, 

thanks for having a look at this. I'm fairly new to Vue 3 as well.
I don't know of a way to assemble a component on the fly, or pass the instance of the parent to the child.
Actually, I tried it with 
```js
this.editor = new Drawflow(id, Vue, this);
```
but still, no vuetify style inside the Nodes.
