### ISSUE TITLE
Please add an after import event

### ISSUE THREAD

**Issue by taroongunessee** [jerosoler/Drawflow#5]
Can we have an event triggered after nodes are imported?  An event handler would be than using a timer to call the updateConnectionNodes method after import

**Comment by jerosoler** [comment]
Hello,

An event could be added.

But I see that you open issue # 1 and # 2 with similar problems, maybe the problem is another.

When calling the "import" method it calls the "load" method that it calls the "updateConnectionNodes" method.

Do you have access to the library to modify it?

Try adding:

```javascript 
this.dispatch ('import', 'import');
```

In: 
```javascript
import (data) {
    this.clear();
    this.drawflow = JSON.parse(JSON.stringify(data));
    this.load();
    this.dispatch ('import', 'import');
  }
```

If this works we add it to the package.

**Comment by taroongunessee** [comment]
Yes, I tried it. Please add the import event.  Thanks a lot

**Comment by jerosoler** [comment]
Added event "import" 

Commit: https://github.com/jerosoler/Drawflow/commit/dd8306c9dfcaaf6eb918970a2fd7932317ce7f05

Update package NPM to 0.0.6

😉
